Repository D2R-Reimagined/d2r-reimagined-mod, pull requests merged in 2024-12, with the labels that each got.

#371 Orb Sprites
  data/hd/global/ui/items/misc/body_part/corruptionorb.lowend.sprite
  data/hd/global/ui/items/misc/body_part/corruptionorb.sprite
  data/hd/global/ui/items/misc/quest/orbofassemblage.lowend.sprite
  data/hd/global/ui/items/misc/quest/orbofassemblage.sprite
  data/hd/global/ui/items/misc/quest/orbofconversion.lowend.sprite
  data/hd/global/ui/items/misc/quest/orbofconversion.sprite
  data/hd/global/ui/items/misc/quest/orbofsocketing.lowend.sprite
  data/hd/global/ui/items/misc/quest/orbofsocketing.sprite
  data/local/lng/strings/item-names.json
Labels: enhancement

#372 Magic Prefix and Suffix String Updates
  data/global/excel/magicprefix.txt
  data/global/excel/magicsuffix.txt
  data/local/lng/strings/item-nameaffixes.json
Labels: bug, enhancement

#370 Update Corruptions in Cubemain
  data/global/excel/cubemain.txt
Labels: enhancement

#374 Key and Key Grabber Sprites
  data/hd/global/ui/items/misc/grabbers/destruction_key_grabber.lowend.sprite
  data/hd/global/ui/items/misc/grabbers/destruction_key_grabber.sprite
  data/hd/global/ui/items/misc/grabbers/hate_key_grabber.lowend.sprite
  data/hd/global/ui/items/misc/grabbers/hate_key_grabber.sprite
  data/hd/global/ui/items/misc/grabbers/terror_key_grabber.lowend.sprite
  data/hd/global/ui/items/misc/grabbers/terror_key_grabber.sprite
  data/hd/global/ui/items/misc/key/destruction_key.lowend.sprite
  data/hd/global/ui/items/misc/key/destruction_key.sprite
  data/hd/global/ui/items/misc/key/terror_key.lowend.sprite
  data/hd/global/ui/items/misc/key/terror_key.sprite
  data/hd/items/items.json
  data/local/lng/strings/item-names.json
Labels: enhancement

#376 Minor Cleanup
  data/global/excel/magicprefix.txt
  data/global/excel/magicsuffix.txt
  data/global/excel/runes.txt
  data/global/excel/sets.txt
  data/local/lng/strings/item-nameaffixes.json
Labels: bug

#379 XP Curve
  data/global/excel/experience.txt
Labels: enhancement

#415 Gem-Rework
  data/global/excel/cubemain.txt
  data/global/excel/gems.txt
  data/global/excel/itemstatcost.txt
  data/global/excel/itemtypes.txt
  data/global/excel/misc.txt
  data/global/excel/properties.txt
  data/global/excel/shrines.txt
  data/global/excel/treasureclassex.txt
  data/global/excel/uniqueitems.txt
  data/hd/items/items.json
  data/local/lng/strings/item-modifiers.json
  data/local/lng/strings/item-names.json
Labels: enhancement
