Repository D2R-Reimagined/d2r-reimagined-mod, pull requests merged in 2025-01, with the labels that each got.

#492 Item Name Corrections
  data/global/excel/setitems.txt
  data/global/excel/sets.txt
  data/global/excel/uniqueitems.txt
  data/hd/items/uniques.json
  data/local/lng/strings/item-names.json
Labels: Format/Fix

#555 Fix Succubus Witch Skills
  data/global/excel/monstats.txt
Labels: bug

#543 Custom Potions
  data/global/excel/misc.txt
  data/global/excel/states.txt
  data/hd/global/ui/items/misc/potion/coldsunderpot.lowend.sprite
  data/hd/global/ui/items/misc/potion/coldsunderpot.sprite
  data/hd/global/ui/items/misc/potion/firesunderpot.lowend.sprite
  data/hd/global/ui/items/misc/potion/firesunderpot.sprite
  data/hd/global/ui/items/misc/potion/lightningsunderpot.lowend.sprite
  data/hd/global/ui/items/misc/potion/lightningsunderpot.sprite
  data/hd/global/ui/items/misc/potion/magicsunderpot.lowend.sprite
  data/hd/global/ui/items/misc/potion/magicsunderpot.sprite
  data/hd/global/ui/items/misc/potion/mfpot1.lowend.sprite
  data/hd/global/ui/items/misc/potion/mfpot1.sprite
  data/hd/global/ui/items/misc/potion/physicalsunderpot.lowend.sprite
  data/hd/global/ui/items/misc/potion/physicalsunderpot.sprite
  data/hd/global/ui/items/misc/potion/poisonsunderpot.lowend.sprite
  data/hd/global/ui/items/misc/potion/poisonsunderpot.sprite
  data/hd/global/ui/items/misc/potion/xppot1.lowend.sprite
  data/hd/global/ui/items/misc/potion/xppot1.sprite
  data/hd/items/items.json
  data/hd/items/misc/potion/coldsunderpot.json
  data/hd/items/misc/potion/firesunderpot.json
  data/hd/items/misc/potion/lightningsunderpot.json
  data/hd/items/misc/potion/magicsunderpot.json
  data/hd/items/misc/potion/mfpot1.json
  data/hd/items/misc/potion/physicalsunderpot.json
  data/hd/items/misc/potion/poisonsunderpot.json
  data/hd/items/misc/potion/xppot1.json
  data/local/lng/strings/item-names.json
Labels: enhancement
